#!/bin/bash

#########################################################
# 
# Platform: NCI Gadi HPC
# Description: filter indels extracted from step 2
# Author: Cali Willet
# cali.willet@sydney.edu.au
# Date last modified: 14/10/2020
#
# If you use this script towards a publication, please acknowledge the
# Sydney Informatics Hub (or co-authorship, where appropriate).
#
# Suggested acknowledgement:
# The authors acknowledge the scientific and technical assistance 
# <or e.g. bioinformatics assistance of <PERSON> of Sydney Informatics
# Hub and resources and services from the National Computational 
# Infrastructure (NCI), which is supported by the Australian Government
# with access facilitated by the University of Sydney.
# 
#########################################################

#PBS -P <project>
#PBS -N bsv-R1-S4
#PBS -l walltime=03:00:00
#PBS -l ncpus=1
#PBS -l mem=32GB
#PBS -l wd
#PBS -q hugemem
#PBS -W umask=022
#PBS -o ./Logs/bsv-R1-S4.o
#PBS -e ./Logs/bsv-R1-S4.e
#PBS -lstorage=<lstorage>

set -e

module load gatk/4.1.2.0 

round=<round>
step=4
type=INDEL

cohort=<cohort>
ref=<ref>
vcf_in=./VCFs/${cohort}_bootstrap-R${round}-S2_${type}_raw.vcf
vcf_out=./VCFs/${cohort}_bootstrap-R${round}-S${step}_${type}_rawFilter.vcf
log=./GATK_logs/Var_filtering_round${round}/${cohort}_bootstrap-R${round}-S${step}_${type}_rawFilter.oe

rm -rf $log

echo "$(date): Bootstrap round ${round} step ${step}: Filter ${type} variants" >> ${log} 2>&1

gatk --java-options "-Xmx29g -DGATK_STACKTRACE_ON_USER_EXCEPTION=true" \
	VariantFiltration \
        -R ${ref} \
        -V ${vcf_in} \
        -O ${vcf_out} \
	-filter-name "QD_filter" -filter "QD < 2.0" \
        -filter-name "FS_filter" -filter "FS > 200.0" \
        -filter-name "SOR_filter" -filter "SOR > 10.0" >> ${log} 2>&1

echo "$(date): Finished." >> ${log} 2>&1

if grep -q -i error $log
then 
        printf "Error in GATK log ${log}\n" 
fi 

if grep -q Exception $log
then 
        printf "Exception in GATK log ${log}\n" 
fi
