#!/bin/bash

#########################################################
# 
# Platform: NCI Gadi HPC
# Description: Consolidate GVCFs with genomics db import
# Result is 3200 VCF GenomicsDImport "databases", 1 for each interval
# Each one is used as input for GenotypeGVCFs
# Author: Cali Willet and Tracy Chew
# cali.willet@sydney.edu.au;tracy.chew@sydney.edu.au
# Date last modified: 14/10/2020
#
# If you use this script towards a publication, please acknowledge the
# Sydney Informatics Hub (or co-authorship, where appropriate).
#
# Suggested acknowledgement:
# The authors acknowledge the scientific and technical assistance 
# <or e.g. bioinformatics assistance of <PERSON> of Sydney Informatics
# Hub and resources and services from the National Computational 
# Infrastructure (NCI), which is supported by the Australian Government
# with access facilitated by the University of Sydney.
# 
#########################################################

#PBS -P <project>
#PBS -N chunk1-bsv-R1-S19
#PBS -l walltime=05:00:00
#PBS -l ncpus=192
#PBS -l mem=5600GB
#PBS -l wd
#PBS -q hugemem
#PBS -W umask=022
#PBS -o ./Logs/bsv-R1-S19-chunk1.o 
#PBS -e ./Logs/bsv-R1-S19-chunk1.e 
#PBS -l storage=<lstorage>


module load openmpi/4.0.2
module load nci-parallel/1.0.0

set -e

round=<round>

mkdir -p ./GenomicsDBImport ./GenomicsDBImport/Round${round} ./GenomicsDBImport/Round${round}/tmp
mkdir -p ./GATK_logs/GenomicsDBImport_round${round} ./Error_capture/GenomicsDBImport_round${round}


SCRIPT=./bsv-R1-S19_genomicsdbimport.sh
INPUTS=./Inputs/genomicsdbimport.inputs-chunk1

NCPUS=6 # CPUs per parallel task



#########################################################
# Do not edit below this line (unless running on a node that 
# does not have 48 CPU, in which case edit the value of 'CPN'
#########################################################

CPN=48 #CPUs per node 
M=$(( CPN / NCPUS )) #tasks per node

sed "s|^|${SCRIPT} |" ${INPUTS} > ${PBS_JOBFS}/input-file

mpirun --np $((M * PBS_NCPUS / 48)) \
        --map-by node:PE=${NCPUS} \
        nci-parallel \
        --verbose \
        --input-file ${PBS_JOBFS}/input-file
	
#########################################################




